spring.application.name=kiusi-hub
spring.datasource.url=jdbc:mysql://localhost:3306/kiusi_hub_db
spring.datasource.username=root
spring.datasource.password=

server.port=8080
app.upload-dir=uploads

# API de tasas de cambio (obtén una clave gratuita en https://v6.exchangerate-api.com/)
exchange.api.key=TU_CLAVE_AQUI
